project/demoapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.MusicianList.as_view(), name='index'),
    url(r'^detail/(?P<pk>\d+)/$', views.MusicianDetail.as_view(), name='musician_detail'),
    url(r'add/$', views.musician_create, name='musician_create'),
]

project/project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('demoapp.urls', namespace='demoapp')),
]

project/demoapp/models.py
from __future__ import unicode_literals

import datetime

from django.utils import timezone
from django.db import models

# Create your models here.

class Musician(models.Model):
    artist_name = models.CharField(max_length=50)

    def __str__(self):              # __unicode__ on Python 2
        return self.artist_name


class Album(models.Model):
    artist = models.ForeignKey(Musician, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    release_date = models.DateField()

    def __str__(self):              # __unicode__ on Python 2
        return self.name

project/demoapp/forms.py
from django import forms
from .models import Album, Musician
from django.forms.models import inlineformset_factory


AlbumFormSet = inlineformset_factory(Musician, Album, fields=['name', 'release_date'], can_delete=False, extra=1)


class MusicianForm(forms.ModelForm):
    artist_name = forms.CharField(label='Artist name', max_length=100,
            widget=forms.TextInput(attrs={'class': 'vTextField', 'placeholder': "Artist's name"}))


    class Meta:
        model = Musician
        fields = ('artist_name',)

project/demoapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect

# Create your views here.
from django.views.generic import ListView, DetailView

from .models import Album, Musician
from .forms import AlbumFormSet, MusicianForm

class MusicianList(ListView):
        model = Musician
        context_object_name = 'musicians'


class MusicianDetail(DetailView):

    model = Musician

    def get_context_data(self, **kwargs):
        # We grab the variable pk from the urlpattern
        artist_id = self.kwargs['pk']

        # Call the base implementation first to get a context
        context = super(MusicianDetail, self).get_context_data(**kwargs)
        context['albums'] = Album.objects.filter(artist_id=artist_id)

        return context


def musician_create(request, template='demoapp/musician_new.html'):

    if request.method == 'POST':
        musician = MusicianForm(request.POST)
        album = AlbumFormSet(request.POST, instance=Musician())

        if musician.is_valid():
            musician = musician.save(commit=False)
            album = AlbumFormSet(request.POST, instance=musician)

            if album.is_valid():
                musician.save()
                album.save()
            return HttpResponseRedirect('/success/')

    # It's not a post, so render the blank form.
    else:
        musician = MusicianForm()
        album = AlbumFormSet(instance=Musician())

    return render(request, template, {'musician': musician,
        'albums': album
    })

project/demoapp/templates/demoapp/musician_detail.html
{% extends "base.html" %}

{% block content %}
    <h2>{{ musician.artist_name }}</h2>
    <ul>
        {% for album in albums %}
        <li>{{ album }}</li>
        {% endfor %}
    </ul>
{% endblock %}

project/demoapp/templates/demoapp/musician_list.html
{% extends "base.html" %}

{% block content %}
    <h2>Musicians</h2>
    <ul>
        {% for musician in musicians %}
          <li><a href="{% url 'demoapp:musician_detail' pk=musician.id %}">{{ musician.artist_name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

project/demoapp/templates/demoapp/musician_new.html
 {% extends 'base.html' %} {% load staticfiles %} {% block extrastyle %}
<!--<script type="text/javascript" src="/admin/jsi18n/"></script>-->
<script type="text/javascript" src="{% static 'admin/jsi18n/' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/core.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/app.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/jquery.init.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/admin/RelatedObjectLookups.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/actions.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/urlify.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/prepopulate.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/vendor/xregexp/xregexp.min.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/inlines.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/calendar.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/admin/DateTimeShortcuts.js' %}"></script>
<meta name="robots" content="NONE,NOARCHIVE" /> {% endblock extrastyle %}
<!-- Content -->
{% block branding %}
<h1>Musician Administration</h1>{% endblock %} {% block content %}
<div id="content" class="colM">
    <h1>Add musician</h1>
    <div id="content-main">
        <form enctype="multipart/form-data" action="" method="post" id="musician_form" novalidate>
            {% csrf_token %}
            <div>
                <fieldset class="module aligned ">
                    <h2>Musician</h2>
                    <div class="form-row">
                        <div>
                            {{ musician.artist_name.label_tag }} {{ musician.artist_name }} {{ musician.artist_name.errors }}
                        </div>
                    </div>
                </fieldset>
                <div class="inline-group" id="album_set-group">
                    <h2>Albums</h2> {% for album in albums %} {{ albums.management_form }}
                    <div class="inline-related dynamic-album_set">
                        <h3><b>Album:</b>&nbsp;<span class="inline_label">#{{ forloop.counter }}</span></h3>
                        <fieldset class="module aligned ">
                            <div class="form-row field-name">
                                <div>
                                    {{ album.name.label_tag }} {{ album.name }} {{ album.name.errors }}
                                </div>
                            </div>
                            <div class="form-row field-release_date">
                                <div class="date-field">
                                    {{ album.release_date.label_tag }} {{ album.release_date }} {{ album.release_date.errors }}
                                </div>
                            </div>
                        </fieldset>
                        {% endfor %}
                    </div>
                    <div class="inline-related empty-form last-related" id="album_set-empty">
                        <h3><b>Album:</b>&nbsp;<span class="inline_label">#2</span></h3>
                        <fieldset class="module aligned ">
                            <div class="form-row field-name">
                                <div>
                                    <label class="required" for="id_album_set-__prefix__-name">Name:</label>
                                    <input class="vTextField" id="id_album_set-__prefix__-name" maxlength="100" name="album_set-__prefix__-name" type="text">
                                </div>
                            </div>
                            <div class="form-row field-release_date">
                                <div>
                                    <label class="required" for="id_album_set-__prefix__-release_date">Release date:</label>
                                    <input class="vDateField" id="id_album_set-__prefix__-release_date" name="album_set-__prefix__-release_date" size="10" type="text"><span class="datetimeshortcuts">&nbsp;<a href="javascript:DateTimeShortcuts.handleCalendarQuickLink(1, 0);">Today</a>&nbsp;|&nbsp;<a href="javascript:DateTimeShortcuts.openCalendar(1);" id="calendarlink1"><span class="date-icon" title="Choose a Date"></span></a>
                                    </span>
                                </div>
                            </div>
                        </fieldset>
                        <input id="id_album_set-__prefix__-id" name="album_set-__prefix__-id" type="hidden">
                        <input id="id_album_set-__prefix__-artist" name="album_set-__prefix__-artist" type="hidden">
                    </div>
                </div>
                <script type="text/javascript">
                (function($) {
                    $("#album_set-group .inline-related").stackedFormset({
                        prefix: "album_set",
                        deleteText: "Remove",
                        addText: "Add another Album"
                    });
                })(django.jQuery);
                </script>
                <div class="submit-row">
                    <input type="submit" value="Save" class="default" name="_save">
                    <input type="submit" value="Save and add another" name="_addanother">
                    <input type="submit" value="Save and continue editing" name="_continue">
                </div>
                <script type="text/javascript">
                (function($) {
                    $(document).ready(function() {
                        $('.add-another').click(function(e) {
                            e.preventDefault();
                            var event = $.Event('django:add-another-related');
                            $(this).trigger(event);
                            if (!event.isDefaultPrevented()) {
                                showAddAnotherPopup(this);
                            }
                        });
                        $('.related-lookup').click(function(e) {
                            e.preventDefault();
                            var event = $.Event('django:lookup-related');
                            $(this).trigger(event);
                            if (!event.isDefaultPrevented()) {
                                showRelatedObjectLookupPopup(this);
                            }
                        });


                        $('form#musician_form :input:visible:enabled:first').focus()

                    });
                })(django.jQuery);
                </script>
                <script type="text/javascript">
                (function($) {
                    var field;


                })(django.jQuery);
                </script>
            </div>
        </form>
    </div>
    <br class="clear" />
</div>
{% endblock %}
<!-- END Content -->
<div id="footer"></div>
<!-- END Container -->

project/demoapp/templates/demoapp/musician_new_custom.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <title>Dynamic Forms in Django Example</title>
    <style type="text/css">
    html {
        background-color: #ededed;
    }
    
    body {
        font-family: Frutiger, "Frutiger Linotype", Univers, Calibri, "Gill Sans", "Gill Sans MT", "Myriad Pro", Myriad, "DejaVu Sans Condensed", "Liberation Sans", "Nimbus Sans L", Tahoma, Geneva, "Helvetica Neue", Helvetica, Arial, sans-serif;
        width: 600px;
        padding: 20px 40px 40px;
        margin: 0 auto;
        margin-top: 15px;
        border: 1px solid #ccc;
        background-color: #fff;
    }
    
    h1 {
        color: #000;
    }
    
    h2 {
        color: #333;
    }
    
    .section,
    .item {
        padding: 0px 15px;
    }
    
    .item {
        background-color: #dcf0f7;
        border: 1px solid #ddd;
        margin-bottom: 4px;
        padding: 5px 15px;
    }
    
    .helptext {
        color: #999;
        padding-left: 10px;
    }
    
    a.delete:hover {
        color: red;
    }
    </style>
    
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript">
   
    </script>
</head>

<body>
    <h1>Demo App</h1>
    <h2>Musician</h2>
    <form enctype="multipart/form-data" action="" method="POST">
        {% csrf_token %}
        <div class="section">
            {{ musician.artist_name.label_tag }} {{ musician.artist_name }} {{ musician.artist_name.errors }}
        </div>
        <h2>Albums</h2> {% for album in albums %}
        <div class="item">
            <div>
                {{ album.name.label_tag }} {{ album.name }} {{ album.name.errors }}
            </div>
            <div>
                {{ album.release_date.label_tag }} {{ album.release_date }} {{ album.release_date.errors }}
            </div>
            <p style=""><a class="delete" href="#">Delete</a></p>
        </div>
        {% endfor %}
        <p><a id="add" href="#">Add another album</a></p>
        <input type="submit" value=" Submit " /> {{ albums.management_form }}
    </form>
</body>

</html>

project/templates/base.html
{% load i18n admin_static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% static 'admin/css/base.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'admin/css/forms.css' %}" />
{% block extrastyle %}{% endblock %}
{% block extrahead %}{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}"
  data-admin-utc-offset="{% now "Z" %}">

<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>
        {% block nav-global %}{% endblock %}
    </div>
    <!-- END Header -->
    <div class="breadcrumbs">
    {% block breadcrumbs %}
    <a href="#">{% trans 'Home' %}</a>
    {% if title %} &rsaquo; {{ title }}{% endif %}
    {% endblock %}
    </div>
    {% endif %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
        {% block content %}{% endblock%}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>
    <!-- END Content -->

    {% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->

</body>
{% block javascript %}{% endblock %}
</html>

project/templates/base_site.html
{% load i18n admin_static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}" />
{% block extrastyle %}{% endblock %}
{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}" />{% endif %}
{% block extrahead %}{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}"
  data-admin-utc-offset="{% now "Z" %}">

<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>
        {% block usertools %}
        {% if has_permission %}
        <div id="user-tools">
            {% block welcome-msg %}
                {% trans 'Welcome,' %}
                <strong>{% firstof user.get_short_name user.get_username %}</strong>.
            {% endblock %}
            {% block userlinks %}
                {% if site_url %}
                    <a href="{{ site_url }}">{% trans 'View site' %}</a> /
                {% endif %}
                {% if user.is_active and user.is_staff %}
                    {% url 'django-admindocs-docroot' as docsroot %}
                    {% if docsroot %}
                        <a href="{{ docsroot }}">{% trans 'Documentation' %}</a> /
                    {% endif %}
                {% endif %}
                {% if user.has_usable_password %}
                <a href="{% url 'admin:password_change' %}">{% trans 'Change password' %}</a> /
                {% endif %}
                <a href="{% url 'admin:logout' %}">{% trans 'Log out' %}</a>
            {% endblock %}
        </div>
        {% endif %}
        {% endblock %}
        {% block nav-global %}{% endblock %}
    </div>
    <!-- END Header -->
    {% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
    {% if title %} &rsaquo; {{ title }}{% endif %}
    </div>
    {% endblock %}
    {% endif %}

    {% block messages %}
        {% if messages %}
        <ul class="messagelist">{% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
        {% endfor %}</ul>
        {% endif %}
    {% endblock messages %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>
    <!-- END Content -->

    {% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->

</body>
</html>